### ISSUE TITLE
not running on Pi with Ubuntu and pi-hole

### ISSUE THREAD

**Issue by thejim** [MatthewVance/stubby-docker#21]
I just did a fresh install of Ubuntu server 20.04.1 LTS on my raspberry pi and installed pi-hole.  I then installed Docker and your  stubby-docker.  Everything seemed to go fine, but when I tried running it, it said there's already something running on port 53 which I'm guessing is the pi-hole though when I run netstat -tulpn it shows the following:

`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:46723         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      -
tcp        0      0 10.0.1.24:53            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp6       0      0 ::1:4711                :::*                    LISTEN      -
tcp6       0      0 :::80                   :::*                    LISTEN      -
tcp6       0      0 fe80::acc8:f287:7c15:53 :::*                    LISTEN      -
tcp6       0      0 ::1:53                  :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
udp        0      0 127.0.0.1:53            0.0.0.0:*                           -
udp        0      0 10.0.1.24:53            0.0.0.0:*                           -
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 10.0.1.24:68            0.0.0.0:*                           -
udp6       0      0 fe80::acc8:f287:7c15:53 :::*                                -
udp6       0      0 ::1:53                  :::*                                -`

so I edited docker-compose.yml and changed the following:

`    ports:
     - "5335:5335/udp"
     - "5335:5335/tcp"`

then when I ran docker-compose up -d it appeared to work.  It now shows:
`stubby-docker_stubby_1 is up-to-date
stubby-docker_unbound_1 is up-to-date`

though nothings showing running on port 5335

But when I go into my pi-hole's DNS settings and enter either 127.0.0.1:5335 or 10.0.1.24:5353 it tells me:
`IP (10.0.1.24:5335) is invalid!
No DNS server has been selected.
The settings have been reset to their previous values`

any ideas what I'm doing wrong?

thank you!

**Comment by MatthewVance** [comment]
See if this info helps:
https://github.com/MatthewVance/unbound-docker/issues/35

Also, this may help: https://docs.docker.com/compose/networking/

**Comment by MatthewVance** [comment]
Did the links I provided help?

**Comment by thejim** [comment]
Hi

I decided not to use stubby but rather just go with pihole and unbound 

Thanks 


Jim Kelley
