### ISSUE TITLE
Have these Stubby features been added to Unbound?

### ISSUE THREAD

**Issue by cyounkins** [MatthewVance/stubby-docker#28]
The README says

> Unbound can be configured as a local forwarder using DNS-over-TLS to forward queries. However at the moment Unbound does not have all the TCP/TLC features that Stubby has for example, it cannot support 'Strict' mode, it cannot pad queries to hide query size and it opens a separate connection for every DNS query (Stubby will re-use connections)

I'm wondering how true this is today with the many updates that Unbound has had.

1. Unbound cannot support 'Strict' mode

AFAIK this describes actual checking of the certificate chain, and I'm pretty sure Unbound does this.

2. Unbound cannot pad queries

There are `pad-*` config options which appear to control this.

3. Unbound opens a separate connection for every DNS query

~~https://dnsprivacy.org/current_work/ says "Unbound version 1.8.3 now supports EDNS(0) Keepalive and TCP connection management". The `edns-tcp-keepalive` config option appeared in 1.8.0 which appears to do this.~~

~~Unbound also appears to support TLS session resumption with the `tls-session-ticket-keys` config option.~~

Is this all correct to your knowledge? Certainly Stubby does things differently and there may be reasons to use it in combination with Unbound outside the above. Thanks!

**Comment by MatthewVance** [comment]
I have not researched the differences in a long time. It’s quite possible Unbound has some (all?) the features now. Being how this README info is dated, I may make it more generic. 

The details should be in the Unbound change log. I’m curious if Stubby has updated the docs that speak to the differences. From a quick look, the info looks similar to what it did years ago. 

https://dnsprivacy.org/dns_privacy_daemon_-_stubby/about_stubby/

I don’t maintain either project so I’m not extremely familiar with the finer points of the implementations. I only offer a Docker option for convenience.

**Comment by cyounkins** [comment]
I'd like to correct my 3rd point above.

Stream reuse was added to Unbound [here](https://github.com/NLnetLabs/unbound/pull/283), merged Nov 24, 2020.

The `edns-tcp-keepalive` option is for TCP/TLS clients connecting to Unbound and does not affect Unbound's connection to upstream. The same is true for TLS session resumption with `tls-session-ticket-keys`

**Comment by MatthewVance** [comment]
Thanks for the update.

For 1, Strict mode in Stubby means "require a TLS connection and authentication of the upstream" and also requires at least one of `ls_auth_name` or `tls_pubkey_pinset` be set. See [here](https://dnsprivacy.org/dns_privacy_daemon_-_stubby/configuring_stubby/).

You're right that Unbound can check the certificate chain (authenticate upstream). This requires configuring a `tls-cert-bundle` to load CA certs. When configuring `forward-addr`, you also need to append a '#' and a name before Unbound will check the tls authentication certificates with that name. The [Actually secure DNS over TLS in Unbound](https://www.ctrl.blog/entry/unbound-tls-forwarding.html) article does a good job of explaining this.

checking of the certificate chain

If Opportunistic mode is desired,  remove the tls_authentication: GETDNS_AUTHENTICATION_REQUIRED field and add additional transports to the dns_transport_list (e.g. UDP, TCP) . In Opportunistic mode authentication of the nameserver is not required and fallback to clear text transports is permitted if they are in the dns_transport_list.

For 2, Unbound can now pad queries. Support for that was added in [1.13.1](https://nlnetlabs.nl/news/2021/Feb/09/unbound-1.13.1-released/), released February 9, 2021.

For 3, the info you provided is accurate. The stream reuse feature now provides that functionality.

I see Stubby as more of a proving ground where newer DNS features are often implemented and available before Unbound receives them. Certainly, the implementation is different. Using them together still provides benefit, but at least for these particular features Unbound has caught up.
