### ISSUE TITLE
[Features] Stack AdGuardHome / Unbound / Cloudflared / Stubby

### ISSUE THREAD

**Issue by oijkn** [MatthewVance/stubby-docker#30]
**Description of the feature**
Create a complete DNS DoH/DoT stack with AdGuardHome / Unbound / Cloudflared / Stubby based on https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare of course without the VPN.

**Benftits of feature**
For a better safety in our environment

**Additional context**
![image](https://user-images.githubusercontent.com/18188407/150191016-ffabb186-ed7d-472d-bfed-c56dc14c5923.png)

**Comment by MatthewVance** [comment]
Hello, thanks for the idea. This isn't something I'm interested in implementing, but you're welcome to fork this and build it.
