### ISSUE TITLE
Issues with Unbound versions later than 1.12.0-stubby 

### ISSUE THREAD

**Issue by rtthane** [MatthewVance/stubby-docker#33]
Hi,

I am currently looking at stubby-docker in my dev environment, but if i try and use any version later than mvance/unbound:1.12.0-stubby I get the following extract of errors when the unbound container is starting. I am using your default config, no custom.

/unbound.sh: line 35: ping: command not found
[1653324116] libunbound[22:0] error: udp connect failed: Cannot assign requested address for 2001:dc3::35 port 53
[1653324230] unbound[1:0] warning: unbound is already running as pid 1.

I have your unbound image running recursively (latest branch) on my prod servers non-Stubby version and it works fine. Same OS version (Ubuntu x64 20.04)

As mentioned it all works fine when using 1.12.0-stubby or earlier.

**Comment by MatthewVance** [comment]
Thanks for the report. This is a known issue in my unbound repo. See this https://github.com/MatthewVance/unbound-docker#known-issues.
