### ISSUE TITLE
Unbound container continually restarting

### ISSUE THREAD

**Issue by jonatj** [MatthewVance/stubby-docker#8]
Built using the latest images of stubby and unbound, then run with "docker-compose up -d". Stubby container starts daemon correctly, but unbound continually restarts with error:

standard_init_linux.go:211: exec user process caused "no such file or directory"

None of the files have been modified.  Running on latest Docker Desktop for Windows 10.

**Comment by MatthewVance** [comment]
Thanks for reporting this issue. How frequently is it restarting? Within
seconds, minutes, hours, etc. I've seen something similar on my standalone
Unbound container running on Raspberry Pi. It's a random restart after
several hours, no pattern. I haven't tracked it down yet but need to. I'm
guessing this is the same one. I hadn't heard any reports of others having
issues until now. Knowing it's not an isolated case concerns me more.

I have not noticed or heard of similar issues on my standalone Unbound
version that's not optimized for ARM processors. Out of curiosity, does
that version work for you without any restart issues? I need to double
check to make sure it is staying up for long periods on my Linux box to be
sure though as the Unbound container bundled with Stubby is fairly similar.
https://github.com/MatthewVance/unbound-docker

When you say running on Windows, is this in a VM or directly in Windows?
I'm not too familiar with Docker on Windows and certainly haven't tested
this in that environment.

**Comment by MatthewVance** [comment]
I just updated Unbound to 1.10.0 and also re-factored the Dockerfile to better match my main Unbound Docker image that does not have any re-start issues as far as I know. Please pull the updated version and re-try.

**Comment by jonatj** [comment]
Thanks Matthew for your responsiveness.  For me the Unbound image was restarting continuously. It never started up, but just had that error.  I’m comfortable with Docker, but I’m new to Stubby and Unbound so I wasn’t sure I was understanding how they were supposed to work.  So I manually installed each on to my server and I got it to work (really well actually). 

But a Docker container would be much easier to manage and support long term. So I’m really looking forward to trying your latest 1.10.0 image.  I’ll give it a try in a couple days and let you know.  

From one “computer guy” to another, it means a lot to me that you’re willing to help me out with this. 

Thank you!
Jonathan 

> On Mar 4, 2020, at 3:18 PM, Matthew Vance <notifications@github.com> wrote:
> 

﻿
I just updated Unbound to 1.10.0 and also re-factored the Dockerfile to better match my main Unbound Docker image that does not have any re-start issues as far as I know. Please pull the updated version and re-try.

**Comment by jonatj** [comment]
Tried it with the 1.10.0 and it works great!

**Comment by MatthewVance** [comment]
Good. Thanks for confirming.
